stages:
  - stage: lint_test
    displayName: 'lint, type-check, test and build'

    jobs:
      - job: verify
        displayName: 'Run verify'

        pool:
          vmImage: 'ubuntu-24.04'

        steps:
          - template: ./pnpm_install.yml

          - task: Bash@3
            displayName: 'Run code checks'
            inputs:
              targetType: 'inline'
              script: |
                pnpm run code

          - task: Bash@3
            displayName: 'Run unit tests'
            inputs:
              targetType: 'inline'
              script: |
                pnpm run test
            env:
              VITE_API_BASE_URL: http://localhost:3000

          - task: Bash@3
            displayName: 'Build'
            inputs:
              targetType: 'inline'
              script: |
                pnpm run build-only
